version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests (requirements.txt, etc.)
    schedule:
      interval: "daily"
    target-branch: "main"
    # By default, all updates (including major) are allowed unless specific ignore
    # conditions or restrictive allowed_updates are set.

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of .github/workflows
    schedule:
      interval: "daily"
    target-branch: "main"
