version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests (requirements.txt, etc.)
    schedule:
      interval: "daily"
    target-branch: "main"
    # By default, only allow patch and minor updates for all pip dependencies.
    # To enable major updates, this section needs to be manually modified
    # (e.g., by commenting out 'allowed_updates' or adding a rule for "semver:major").
    allowed_updates:
      - match:
          dependency-name: "*" # Apply to all pip dependencies
          update-type: "semver:patch"
      - match:
          dependency-name: "*" # Apply to all pip dependencies
          update-type: "semver:minor"

  # Enable version updates for GitHub Actions
  # By default, this allows all updates for GitHub Actions, including major versions.
  # Add allowed_updates or ignore rules here if you want to restrict action updates.
  - package-ecosystem: "github-actions"
    directory: "/" # Location of .github/workflows
    schedule:
      interval: "daily"
    target-branch: "main"
