# Game world configuration
WORLD_SIZE = (3000, 3000)
SCROLL_TRIGGER = 0.1

# Gameplay constants
CARROT_RESPAWN_DELAY = 3
BULLET_SPEED = 10
GARLIC_SHOT_SPEED = 5
MAX_HEALTH = 3
MAX_GARLIC = 3
MAX_SPEED_MULTIPLIER = 3
CARROT_COUNT = 5
GARLIC_SHOT_DURATION = 3
GARLIC_SHOT_MAX_TRAVEL = 250
GARLIC_ROTATION_SPEED = 5

# Entity properties
CARROT_DETECTION_RADIUS = 200
CARROT_CHASE_RADIUS = 100
ITEM_SCALE = 0.5

# UI constants
ITEM_WIDTH = 32
ITEM_HEIGHT = 32
BUTTON_SPACING = 20

# Additional gameplay constants
GARLIC_SHOT_DURATION = 3
EXPLOSION_FLASH_INTERVAL = 0.1
EXPLOSION_MAX_FLASHES = 3
FRAME_DELAY = 0.02
VAMPIRE_SPEED = 4
CARROT_SPEED = 3
PLAYER_SPEED = 3
