# Game world configuration
WORLD_SIZE = (3000, 3000)
SCROLL_TRIGGER = 0.1

# Gameplay constants
CARROT_RESPAWN_DELAY = 3
BULLET_SPEED = 10
GARLIC_SHOT_SPEED = 5
MAX_HEALTH = 3
MAX_GARLIC = 3
MAX_SPEED_MULTIPLIER = 3
CARROT_COUNT = 5

# Entity properties
CARROT_DETECTION_RADIUS = 200
CARROT_CHASE_RADIUS = 100
