name: Run Project Tests

on:
  push:
    branches: [ '**' ] # Run on pushes to any branch
  pull_request:
    branches: [ main ] # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If requirements_dev.txt exists and is needed for tests:
        if [ -f requirements_dev.txt ]; then
          pip install -r requirements_dev.txt
        fi

    - name: Run Pytest
      run: |
        python -m pytest -v
