name: Toggle Dependabot Major Updates for Pip

on:
  workflow_dispatch:
    inputs:
      major_updates_enabled:
        description: 'Enable major updates for Pip dependencies? (true/false)'
        required: true
        type: boolean
        default: false

jobs:
  update_dependabot_config:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the workflow to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }} # Checkout the branch the workflow is running on (e.g. main)

      - name: Update Dependabot Configuration File
        run: |
          set -e # Exit on error
          MAJOR_UPDATES_ENABLED="${{ github.event.inputs.major_updates_enabled }}"
          DEPENDABOT_FILE=".github/dependabot.yml" # Define for cat command later

          echo "Input major_updates_enabled: $MAJOR_UPDATES_ENABLED"

          if [[ "$MAJOR_UPDATES_ENABLED" == "true" ]]; then
            echo "Executing: bash .github/scripts/set_dependabot_permissive.sh"
            bash .github/scripts/set_dependabot_permissive.sh
          else
            echo "Executing: bash .github/scripts/set_dependabot_restrictive.sh"
            bash .github/scripts/set_dependabot_restrictive.sh
          fi

          echo "Content of $DEPENDABOT_FILE after update:"
          cat $DEPENDABOT_FILE

      - name: Commit and Push Dependabot Configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/dependabot.yml

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to dependabot.yml. Configuration already matches desired state."
          else
            COMMIT_MESSAGE="chore(dependabot): Set pip major updates to ${{ github.event.inputs.major_updates_enabled }}"
            echo "Committing with message: $COMMIT_MESSAGE"
            git commit -m "$COMMIT_MESSAGE"

            # Extract branch name from ref (e.g., refs/heads/main -> main)
            # GITHUB_REF is in format refs/heads/branch-name or refs/tags/tag-name or refs/pull/pr-number/merge
            # We only want to push if it's a branch.
            if [[ "${{ github.ref }}" == refs/heads/* ]]; then
              BRANCH_NAME=${GITHUB_REF#refs/heads/}
              echo "Pushing changes to branch $BRANCH_NAME..."
              git push origin "$BRANCH_NAME"
              echo "Committed and pushed changes to dependabot.yml on branch $BRANCH_NAME"
            else
              echo "Workflow not running on a branch head (ref: ${{ github.ref }}). Skipping push."
              echo "This is normal for tag events or PRs if the workflow were triggered by them."
              echo "For workflow_dispatch, GITHUB_REF should be the branch it was triggered from."
            fi
          fi
